Interactivelist
samuelkinyanjui/ToDolistsm pull request #3
Opened 2023-07-21 19:46 UTC by samuelkinyanjui

Add a new JavaScript file and import it as a module:
it will contain methods related to the status updates (completed: true / false).
Add event listener to the checkbox (change).
Update items object's value for completed key upon user actions.
Implement a function for the "Clear all completed" button (use filter() method).
Store the updated array of items in local storage, so the user gets the correct list of values after the page reloads (which means that any changes made to the list should be preserved).

2023-07-21 20:03 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @samuelkinyanjui 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
❌ add and remove methods are missing
❌ the project requirements aren't been met
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 20:03 UTC, tugsem commented on src/index.js
> +  },
- [ ] Please remove all of the hardcoded tasks as it was the previous task's requirement.

2023-07-21 20:03 UTC, tugsem commented on src/index.js
> +        `;
- [ ] I think there is a problem with your current code. You should render the items from the local storage and should have modules for adding, removing books and updating the local storage. But you only rendering the hardcoded items and adding book is not working.  Please add modules for adding and removing books, then, you should implement these:
- [ ] Add a module for updating status changes
- [ ] Add an event handler for checkboxes
- [ ] Add a module for clearing all completed items.
- [ ] Save all of the changes to the local storage

2023-07-22 20:36 UTC, skyv26 approved these changes
## Hi @samuelkinyanjui, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWRlMTU1MTgyOWI3OTNiMGUxOWQ3NTUxNDc4YWE5MTY0YWFmNmEwYyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Ti0pkgccBnF7Xy1vhk/giphy-downsized-large.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Linters are green ✅ 
- Correct `.github/workflows` for linters ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 11:02 UTC, Uzair-Manzoor commented on README.md
> +
**Incorrect command:** In the Usage section, there is an inconsistency between the provided command and the description. The description mentions running the project with the command `npm install`, which is incorrect. It should be something like `npm run build` and `npm start` instead.

2023-08-05 06:46 UTC, closed without merging

2023-08-05 06:47 UTC, samuelkinyanjui commented
Implemented the changes